"""Write references.bib for the 12-page version from ../tse_latex/references.bib.

IEEEtran.bst ignores the doi field, so the two entries a reader must be able to
follow, the replication package and the extended version, get the DOI as a
url field here. The shared bibliography stays as it is, because the EMSE build
prints DOIs itself and would print the link twice.

    python paper/short_latex/make_bib.py
"""
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
src = (HERE.parent / "tse_latex" / "references.bib").read_text(encoding="utf-8")
LINKED = {"replication", "extended"}

out = []
for entry in re.split(r"\n(?=@)", src):
    m = re.match(r"@\w+\{([^,]+),", entry.strip())
    if m and m.group(1) in LINKED and not re.search(r"\burl\s*=", entry):
        doi = re.search(r"\bdoi\s*=\s*\{([^}]*)\}", entry)
        if doi:
            entry = entry.replace(m.group(0), m.group(0) + f"\n  url          = {{https://doi.org/{doi.group(1)}}},", 1)
    out.append(entry)
header = "% Generated by make_bib.py from ../tse_latex/references.bib; edit that file.\n"
(HERE / "references.bib").write_text(header + "\n".join(out), encoding="utf-8")
print("wrote", HERE / "references.bib")
