"""Generate the per-instance table of the twelve frozen instances (A3 R2a).

Reads benchmark/a3_results.json (written by analyze_a3.py) and the transport
errors kept in scripts/runs/2026-09-30_fabbench12/transport_errors/, and writes
paper/emse_latex/table_fabbench12.tex. Generated, never typed: a table typed
by hand was fault 11.

    python -X utf8 scripts/table_fabbench12.py
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from analyze_revision_runs import wilson  # noqa: E402

RES = json.loads((ROOT / "benchmark" / "a3_results.json").read_text(encoding="utf-8"))["R2"]
ERR = ROOT / "scripts" / "runs" / "2026-09-30_fabbench12" / "transport_errors"
OUT = ROOT / "paper" / "emse_latex" / "table_fabbench12.tex"
NAMES = {"insurance.csv": "insurance", "heart_cleveland.csv": "heart",
         "telco_churn.csv": "telco", "ames_housing.csv": "Ames"}


def lost(task: str) -> int:
    _, rest = task.split(":", 1)
    csv, target, inj = rest.split("/")
    pat = f"*csv-{csv}-{target}-{inj}_layer1_*.jsonl"
    return sum(sum(1 for _ in f.open(encoding="utf-8")) for f in ERR.glob(pat))


rows = []
tot = {"n": 0, "lost": 0, "k": 0, "mis": 0, "unl": 0, "inv": 0}
for task, v in sorted(RES["instances"].items(), key=lambda kv: kv[0]):
    f = v["A-L1"]
    csv, _, inj = task.split(":", 1)[1].split("/")
    lo, hi = wilson(f["entity"], f["n"])
    n_lost = lost(task)
    rows.append(
        f"{NAMES[csv]} & \\texttt{{{inj.replace('_', chr(92) + '_')}}} & {f['n']} & {n_lost} & "
        f"{f['entity']} & {100 * f['entity'] / f['n']:.1f} [{lo:.1f}, {hi:.1f}] & "
        f"{f['misfiled']} & {f['unlisted']} & {f['invented']} \\\\"
    )
    for key, val in (("n", f["n"]), ("lost", n_lost), ("k", f["entity"]),
                     ("mis", f["misfiled"]), ("unl", f["unlisted"]), ("inv", f["invented"])):
        tot[key] += val

body = "\n".join(rows)
OUT.write_text(
    r"""\begin{table}[!htbp]
\caption{The floor arm (\texttt{A-L1}) on the twelve instances frozen on
2026-07-07, \texttt{deepseek-chat}, 200 calls each. \emph{Lost}: calls that
returned a transport error when the provider balance ran out, excluded from
$N$ (amendment A4). \emph{Flagged}: responses with an entity violation, with
the Wilson 95\,\% interval. The last three columns count responses containing
at least one name of that kind, so a response can appear in more than one.
Generated by \texttt{scripts/table\_fabbench12.py}.}
\label{tab:fabbench12}
\centering
\footnotesize
\begin{tabular}{@{}llrrrlrrr@{}}
\toprule
Table & Leak & $N$ & Lost & Flagged & \% [95\,\% CI] & Misfiled & Unlisted & Invented \\
\midrule
""" + body + "\n\\midrule\n"
    + f"All & & {tot['n']:,} & {tot['lost']} & {tot['k']} & & {tot['mis']} & {tot['unl']} & {tot['inv']} \\\\\n".replace(",", "{,}")
    + r"""\bottomrule
\end{tabular}
\end{table}
""",
    encoding="utf-8",
)
print(f"wrote {OUT}: N={tot['n']} lost={tot['lost']} flagged={tot['k']}")
